# docker-compose.yml

version: '3.9'
services:
    boofuzz:
        build:
            context: ../../
            dockerfile: ./Dockerfile
        volumes:
            - ./fuzzer.py:/fuzzer.py
        command: python3 /fuzzer.py
        networks:
            - fuzz_network
        ports:
            - 26000:26000
    netflix-cve:
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - fuzz_network
networks:
    fuzz_network:
