# docker-compose.yml

version: '3.9'
services:
    boofuzz:
        build:
            context: ../../
            dockerfile: ./Dockerfile
        volumes:
            - ./fuzzer.py:/fuzzer.py
        command: "python3 /fuzzer.py > /dev/null"
        links:
            - netflix-dial:dialserver
        networks:
            - default
            - dock_net
        ports:
            - 26000:26000
    netflix-dial:
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - dock_net
networks:
    dock_net:
        driver: ipvlan
